//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication17.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerRole
    {
        public int ID { get; set; }
        public Nullable<int> IdCustomer { get; set; }
        public Nullable<int> IdRole { get; set; }

        internal virtual Customer Customer { get; set; }
        internal virtual Role Role { get; set; }
    }
}
